import { AAVE_V3_BASE, AAVE_V3_WITHDRAW_SELECTOR, canonicalRoleKey } from "@exit-keepa/shared";
import { concatHex, encodeAbiParameters, encodeFunctionData, hashTypedData, keccak256, stringToHex, type Hex } from "viem";
import { env } from "../env";
import { HttpError } from "../middleware/errorHandler";

export const SAFE_ZERO_ADDRESS = "0x0000000000000000000000000000000000000000" as const;
export const SAFE_V1_4_1_SINGLETON = "0x41675C099F32341bf84BFc5382aF534df5C7461a" as const;
export const ROLES_V2_1_1_MASTER_COPY = "0xF2964CE6161ce0e75964Fe7927cE114cb0B283D5" as const;
export const ROLES_V2_1_0_MASTER_COPY = "0x9646fDAD06d3e24444381f44362a3B0eB343D337" as const;
export const ZODIAC_MODULE_PROXY_FACTORY = "0x000000000000000000000000000000000000aDdB49795b0f9bA5BC298cDda236" as const;
export const KEEPERHUB_EXECUTION_SENDER = "0xc68f0E22Dc6eD7e883873B36f23DdBBC1b3968Ac" as const;

const SENTINEL_MODULES = "0x0000000000000000000000000000000000000001" as const;
const MODULE_PROXY_PREFIX = "602d8060093d393df3363d3d373d3d3d363d73";
const MODULE_PROXY_SUFFIX = "5af43d82803e903d91602b57fd5bf3";
const DEPLOY_SELECTOR = keccak256(stringToHex("deployModule(address,bytes,uint256)")).slice(0, 10).toLowerCase();
// Roles v2.1.1 storage: avatar=0, target=1, modules=2, consumed=3, roles=4.
const ROLES_MAPPING_SLOT = 4n;

const SAFE_TX_TYPES = { SafeTx: [
  { name: "to", type: "address" }, { name: "value", type: "uint256" }, { name: "data", type: "bytes" }, { name: "operation", type: "uint8" },
  { name: "safeTxGas", type: "uint256" }, { name: "baseGas", type: "uint256" }, { name: "gasPrice", type: "uint256" }, { name: "gasToken", type: "address" },
  { name: "refundReceiver", type: "address" }, { name: "nonce", type: "uint256" },
] } as const;
const ROLES_ABI = [
  { type: "function", name: "setUp", stateMutability: "nonpayable", inputs: [{ name: "initParams", type: "bytes" }], outputs: [] },
  { type: "function", name: "assignRoles", stateMutability: "nonpayable", inputs: [{ name: "module", type: "address" }, { name: "roleKeys", type: "bytes32[]" }, { name: "memberOf", type: "bool[]" }], outputs: [] },
  { type: "function", name: "scopeTarget", stateMutability: "nonpayable", inputs: [{ name: "roleKey", type: "bytes32" }, { name: "targetAddress", type: "address" }], outputs: [] },
  { type: "function", name: "scopeFunction", stateMutability: "nonpayable", inputs: [{ name: "roleKey", type: "bytes32" }, { name: "targetAddress", type: "address" }, { name: "selector", type: "bytes4" }, { name: "conditions", type: "tuple[]", components: [{ name: "parent", type: "uint8" }, { name: "paramType", type: "uint8" }, { name: "operator", type: "uint8" }, { name: "compValue", type: "bytes" }] }, { name: "options", type: "uint8" }], outputs: [] },
] as const;
const FACTORY_ABI = [{ type: "function", name: "deployModule", stateMutability: "nonpayable", inputs: [{ name: "masterCopy", type: "address" }, { name: "initializer", type: "bytes" }, { name: "saltNonce", type: "uint256" }], outputs: [{ name: "proxy", type: "address" }] }] as const;
const SAFE_READ_ABI = [
  { type: "function", name: "getOwners", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address[]" }] },
  { type: "function", name: "getThreshold", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "nonce", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "VERSION", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "masterCopy", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "getTransactionHash", stateMutability: "view", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }, { name: "data", type: "bytes" }, { name: "operation", type: "uint8" }, { name: "safeTxGas", type: "uint256" }, { name: "baseGas", type: "uint256" }, { name: "gasPrice", type: "uint256" }, { name: "gasToken", type: "address" }, { name: "refundReceiver", type: "address" }, { name: "_nonce", type: "uint256" }], outputs: [{ name: "", type: "bytes32" }] },
] as const;
const EXEC_TRANSACTION_ABI = [{ type: "function", name: "execTransaction", stateMutability: "payable", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }, { name: "data", type: "bytes" }, { name: "operation", type: "uint8" }, { name: "safeTxGas", type: "uint256" }, { name: "baseGas", type: "uint256" }, { name: "gasPrice", type: "uint256" }, { name: "gasToken", type: "address" }, { name: "refundReceiver", type: "address" }, { name: "signatures", type: "bytes" }], outputs: [{ name: "success", type: "bool" }] }] as const;
const MODULE_READ_ABI = [
  { type: "function", name: "isModuleEnabled", stateMutability: "view", inputs: [{ name: "module", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "getModulesPaginated", stateMutability: "view", inputs: [{ name: "start", type: "address" }, { name: "pageSize", type: "uint256" }], outputs: [{ name: "array", type: "address[]" }, { name: "next", type: "address" }] },
] as const;
const ROLE_EXEC_ABI = [{ type: "function", name: "execTransactionWithRole", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }, { name: "data", type: "bytes" }, { name: "operation", type: "uint8" }, { name: "roleKey", type: "bytes32" }, { name: "shouldRevert", type: "bool" }], outputs: [{ name: "success", type: "bool" }] }] as const;
const WITHDRAW_ABI = [{ type: "function", name: "withdraw", stateMutability: "nonpayable", inputs: [{ name: "asset", type: "address" }, { name: "amount", type: "uint256" }, { name: "to", type: "address" }], outputs: [{ name: "", type: "uint256" }] }] as const;

type SafeTx = { to: `0x${string}`; value: bigint; data: Hex; operation: 0; safeTxGas: bigint; baseGas: bigint; gasPrice: bigint; gasToken: `0x${string}`; refundReceiver: `0x${string}`; nonce: bigint };
async function rpc(method: string, params: unknown[]): Promise<unknown> { const response = await fetch(env.BASE_RPC_URL, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }) }); if (!response.ok) throw new HttpError(502, "Could not verify your Safe. Try again."); const body = await response.json() as { result?: unknown; error?: { message?: string } }; if (body.error) throw new HttpError(409, body.error.message ?? "Safe verification failed"); return body.result; }
async function rpcCall(to: string, data: Hex, from?: string): Promise<string> { const result = await rpc("eth_call", [{ to, data, ...(from ? { from } : {}) }, "latest"]); if (typeof result !== "string" || !result) throw new HttpError(409, "Safe verification returned no result"); return result; }
async function rpcCode(address: string): Promise<string> { const result = await rpc("eth_getCode", [address, "latest"]); if (typeof result !== "string") throw new HttpError(409, "Safe verification returned no code"); return result; }
async function rpcStorage(address: string, slot: Hex): Promise<Hex> { const result = await rpc("eth_getStorageAt", [address, slot, "latest"]); if (typeof result !== "string" || !/^0x[0-9a-fA-F]{64}$/.test(result)) throw new HttpError(409, "Safe permission state could not be read."); return result as Hex; }
function decodeAddressArray(hex: string): string[] { const body = hex.slice(2); if (body.length < 64) throw new HttpError(409, "Safe owner data could not be decoded"); const offset = Number(BigInt(`0x${body.slice(0, 64)}`)) * 2; const length = Number(BigInt(`0x${body.slice(offset, offset + 64)}`)); const result: string[] = []; for (let i = 0; i < length; i++) { const start = offset + 64 + i * 64; if (body.length < start + 64) throw new HttpError(409, "Safe owner data could not be decoded"); result.push(`0x${body.slice(start + 24, start + 64)}`); } return result; }
function decodeString(hex: string): string { const body = hex.slice(2); const offset = Number(BigInt(`0x${body.slice(0, 64)}`)) * 2; const length = Number(BigInt(`0x${body.slice(offset, offset + 64)}`)); return Buffer.from(body.slice(offset + 64, offset + 64 + length * 2), "hex").toString("utf8"); }
function parseRolesImplementation(code: string): string | null { const body = code.toLowerCase().replace(/^0x/, ""); const prefix = "363d3d373d3d3d363d73"; const suffix = "5af43d82803e903d91602b57fd5bf3"; if (!body.startsWith(prefix) || !body.endsWith(suffix) || body.length !== 90) return null; return `0x${body.slice(prefix.length, prefix.length + 40)}`; }
export async function inspectSafeForAuthorization(safeAddress: `0x${string}`, connectedOwner: `0x${string}`) { const [ownersRaw, thresholdRaw, nonceRaw, versionRaw, masterCopyRaw, code] = await Promise.all([rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "getOwners" })), rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "getThreshold" })), rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "nonce" })), rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "VERSION" })), rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "masterCopy" })), rpcCode(safeAddress)]); const owners = decodeAddressArray(ownersRaw); const masterCopy = `0x${masterCopyRaw.slice(-40)}`; return { owners, threshold: Number(BigInt(thresholdRaw)), nonce: BigInt(nonceRaw), version: decodeString(versionRaw), masterCopy, isOwner: owners.some((owner) => owner.toLowerCase() === connectedOwner.toLowerCase()), isSafe: code !== "0x" && masterCopy.toLowerCase() === SAFE_V1_4_1_SINGLETON.toLowerCase() }; }
export async function verifyRolesModifier(modifierAddress: `0x${string}`, safeAddress: `0x${string}`) { const implementation = parseRolesImplementation(await rpcCode(modifierAddress)); if (!implementation || implementation.toLowerCase() !== ROLES_V2_1_1_MASTER_COPY.toLowerCase()) return false; const [avatarRaw, targetRaw, ownerRaw] = await Promise.all([rpcCall(modifierAddress, "0x5aef7de6"), rpcCall(modifierAddress, "0xd4b83992"), rpcCall(modifierAddress, "0x8da5cb5b")]); const safe = safeAddress.toLowerCase(); return `0x${avatarRaw.slice(-40)}`.toLowerCase() === safe && `0x${targetRaw.slice(-40)}`.toLowerCase() === safe && `0x${ownerRaw.slice(-40)}`.toLowerCase() === safe; }
export async function classifyRolesModule(modifierAddress: `0x${string}`, safeAddress: `0x${string}`): Promise<"compatible" | "incompatible_roles" | "other"> { const implementation = parseRolesImplementation(await rpcCode(modifierAddress)); if (!implementation) return "other"; if (implementation.toLowerCase() === ROLES_V2_1_1_MASTER_COPY.toLowerCase()) return (await verifyRolesModifier(modifierAddress, safeAddress)) ? "compatible" : "incompatible_roles"; return "incompatible_roles"; }
export async function verifyFactory(): Promise<void> { const code = await rpcCode(ZODIAC_MODULE_PROXY_FACTORY); if (code === "0x" || code.length <= 2) throw new HttpError(503, "Automatic Safe setup is unavailable because the verified module factory is not deployed on Base."); if (!code.toLowerCase().includes(DEPLOY_SELECTOR.slice(2))) throw new HttpError(503, "Automatic Safe setup is unavailable because the verified module factory is not the expected Zodiac factory."); }
function safeTxTypedData(safeAddress: `0x${string}`, tx: SafeTx, chainId: number) { return { domain: { chainId, verifyingContract: safeAddress }, types: SAFE_TX_TYPES, primaryType: "SafeTx" as const, message: { to: tx.to, value: tx.value, data: tx.data, operation: tx.operation, safeTxGas: tx.safeTxGas, baseGas: tx.baseGas, gasPrice: tx.gasPrice, gasToken: tx.gasToken, refundReceiver: tx.refundReceiver, nonce: tx.nonce } }; }
function addressCompValue(address: `0x${string}`): Hex { return encodeAbiParameters([{ type: "address" }], [address]); }
export function buildRoleConfigurationCalls(safeAddress: `0x${string}`, keeperAddress: `0x${string}`) { const roleKey = canonicalRoleKey(); const assignRoles = encodeFunctionData({ abi: ROLES_ABI, functionName: "assignRoles", args: [keeperAddress, [roleKey], [true]] }); const scopeTarget = encodeFunctionData({ abi: ROLES_ABI, functionName: "scopeTarget", args: [roleKey, AAVE_V3_BASE.pool] }); const conditions = [{ parent: 0, paramType: 5, operator: 5, compValue: "0x" as Hex }, { parent: 0, paramType: 1, operator: 16, compValue: addressCompValue(AAVE_V3_BASE.usdc) }, { parent: 0, paramType: 1, operator: 0, compValue: "0x" as Hex }, { parent: 0, paramType: 1, operator: 16, compValue: addressCompValue(safeAddress) }] as const; const scopeFunction = encodeFunctionData({ abi: ROLES_ABI, functionName: "scopeFunction", args: [roleKey, AAVE_V3_BASE.pool, AAVE_V3_WITHDRAW_SELECTOR, conditions, 0] }); return [{ id: "assign-role", label: "Authorize the Exit Keepa keeper", kind: "assign_role" as const, data: assignRoles }, { id: "scope-target", label: "Restrict the role to Aave on Base", kind: "scope_target" as const, data: scopeTarget }, { id: "scope-function", label: "Restrict the role to the USDC withdrawal", kind: "scope_function" as const, data: scopeFunction }] as const; }
export function buildSafeTransaction(args: { to: `0x${string}`; data: Hex; nonce: bigint }): SafeTx { return { to: args.to, value: 0n, data: args.data, operation: 0, safeTxGas: 0n, baseGas: 0n, gasPrice: 0n, gasToken: SAFE_ZERO_ADDRESS, refundReceiver: SAFE_ZERO_ADDRESS, nonce: args.nonce }; }
export function computeSafeTransactionHash(safeAddress: `0x${string}`, tx: SafeTx, chainId: number): Hex { return hashTypedData(safeTxTypedData(safeAddress, tx, chainId)); }
export function buildTypedDataForSafeTransaction(safeAddress: `0x${string}`, tx: SafeTx, chainId: number) { return safeTxTypedData(safeAddress, tx, chainId); }
export function encodeExecTransaction(tx: SafeTx, signatures: Hex): Hex { return encodeFunctionData({ abi: EXEC_TRANSACTION_ABI, functionName: "execTransaction", args: [tx.to, tx.value, tx.data, tx.operation, tx.safeTxGas, tx.baseGas, tx.gasPrice, tx.gasToken, tx.refundReceiver, signatures] }); }
export async function verifySafeTransactionHash(safeAddress: `0x${string}`, tx: SafeTx, chainId: number) { const localHash = computeSafeTransactionHash(safeAddress, tx, chainId); const raw = await rpcCall(safeAddress, encodeFunctionData({ abi: SAFE_READ_ABI, functionName: "getTransactionHash", args: [tx.to, tx.value, tx.data, tx.operation, tx.safeTxGas, tx.baseGas, tx.gasPrice, tx.gasToken, tx.refundReceiver, tx.nonce] })); const onchainHash = `0x${raw.slice(-64)}` as Hex; if (localHash.toLowerCase() !== onchainHash.toLowerCase()) throw new HttpError(409, "Could not verify the Safe transaction hash. Nothing was signed."); return { localHash, onchainHash }; }
export function buildRolesInitializer(safeAddress: `0x${string}`): Hex { const initParams = encodeAbiParameters([{ type: "address" }, { type: "address" }, { type: "address" }], [safeAddress, safeAddress, safeAddress]); return encodeFunctionData({ abi: ROLES_ABI, functionName: "setUp", args: [initParams] }); }
export function deriveModuleSaltNonce(safeAddress: `0x${string}`): bigint { return BigInt(keccak256(concatHex([stringToHex("exit-keepa:roles"), safeAddress as Hex]))); }
export function predictModuleProxyAddress(safeAddress: `0x${string}`, saltNonce: bigint): `0x${string}` { const initializer = buildRolesInitializer(safeAddress); const salt = keccak256(concatHex([keccak256(initializer), `0x${saltNonce.toString(16).padStart(64, "0")}`])); const deployment = (`0x${MODULE_PROXY_PREFIX}${ROLES_V2_1_1_MASTER_COPY.slice(2).toLowerCase()}${MODULE_PROXY_SUFFIX}`) as Hex; const addressHash = keccak256(concatHex(["0xff", ZODIAC_MODULE_PROXY_FACTORY, salt, keccak256(deployment)])); return `0x${addressHash.slice(-40)}`; }
export function buildDeployModuleTransaction(safeAddress: `0x${string}`) { const saltNonce = deriveModuleSaltNonce(safeAddress); const initializer = buildRolesInitializer(safeAddress); const predictedProxy = predictModuleProxyAddress(safeAddress, saltNonce); const data = encodeFunctionData({ abi: FACTORY_ABI, functionName: "deployModule", args: [ROLES_V2_1_1_MASTER_COPY, initializer, saltNonce] }); return { to: ZODIAC_MODULE_PROXY_FACTORY as `0x${string}`, value: "0x0", data, operation: 0 as const, saltNonce, predictedProxy }; }
export async function inspectEnabledModules(safeAddress: `0x${string}`): Promise<string[]> { const modules: string[] = []; let start = SENTINEL_MODULES; for (let page = 0; page < 10_000; page++) { const raw = await rpcCall(safeAddress, encodeFunctionData({ abi: MODULE_READ_ABI, functionName: "getModulesPaginated", args: [start, 20n] })); const body = raw.slice(2); const offset = Number(BigInt(`0x${body.slice(0, 64)}`)) * 2; const arrayLength = Number(BigInt(`0x${body.slice(offset, offset + 64)}`)); for (let i = 0; i < arrayLength; i++) { const startWord = offset + 64 + i * 64; modules.push(`0x${body.slice(startWord + 24, startWord + 64)}`); } const nextWord = offset + 64 + arrayLength * 64; const next = `0x${body.slice(nextWord + 24, nextWord + 64)}`; if (next.toLowerCase() === SENTINEL_MODULES.toLowerCase()) return modules; if (arrayLength === 0) throw new HttpError(409, "Safe module pagination could not be verified."); start = next; } throw new HttpError(409, "Safe module pagination exceeded the verification limit."); }
export async function verifyEnabledModule(safeAddress: `0x${string}`, moduleAddress: `0x${string}`): Promise<boolean> { const raw = await rpcCall(safeAddress, encodeFunctionData({ abi: MODULE_READ_ABI, functionName: "isModuleEnabled", args: [moduleAddress] })); return BigInt(raw) !== 0n; }
function mappingSlot(key: Hex, slot: bigint): Hex { return keccak256(encodeAbiParameters([{ type: "bytes32" }, { type: "uint256" }], [key, slot])); }
function nestedMappingSlot(key: `0x${string}`, parentSlot: Hex): Hex { return keccak256(encodeAbiParameters([{ type: "address" }, { type: "bytes32" }], [key, parentSlot])); }
function roleStructBase(roleKey: Hex): Hex { return mappingSlot(roleKey, ROLES_MAPPING_SLOT); }
function roleMemberSlot(roleKey: Hex, member: `0x${string}`): Hex { return nestedMappingSlot(member, roleStructBase(roleKey)); }
function roleTargetSlot(roleKey: Hex, target: `0x${string}`): Hex { const base = BigInt(roleStructBase(roleKey)) + 1n; return nestedMappingSlot(target, `0x${base.toString(16).padStart(64, "0")}`); }
function roleScopeSlot(roleKey: Hex, target: `0x${string}`, selector: `0x${string}`): Hex { const targetSelectorKey = (`0x${target.slice(2).toLowerCase()}${selector.slice(2).toLowerCase()}${"0".repeat(16)}`) as Hex; const base = BigInt(roleStructBase(roleKey)) + 2n; return mappingSlot(targetSelectorKey, base); }
function decodeRoleHeader(header: Hex) { const value = BigInt(header); return { count: Number((value >> 240n) & 0xffffn), options: Number((value >> 224n) & 0xffn), wildcarded: ((value >> 216n) & 1n) === 1n, pointer: `0x${(value & ((1n << 160n) - 1n)).toString(16).padStart(40, "0")}` as `0x${string}` }; }
export async function readRolePermissionState(modifierAddress: `0x${string}`, safeAddress: `0x${string}`, memberAddress: `0x${string}`) { const roleKey = canonicalRoleKey(); const [memberWord, targetWord, scopeHeader] = await Promise.all([rpcStorage(modifierAddress, roleMemberSlot(roleKey, memberAddress)), rpcStorage(modifierAddress, roleTargetSlot(roleKey, AAVE_V3_BASE.pool)), rpcStorage(modifierAddress, roleScopeSlot(roleKey, AAVE_V3_BASE.pool, AAVE_V3_WITHDRAW_SELECTOR))]); const memberAssigned = (BigInt(memberWord) & 0xffn) === 1n; const targetValue = BigInt(targetWord); const targetScoped = Number(targetValue & 0xffn) === 2 && Number((targetValue >> 8n) & 0xffn) === 0; const header = decodeRoleHeader(scopeHeader); let functionScoped = false; if (header.count === 4 && header.options === 0 && !header.wildcarded && header.pointer !== SAFE_ZERO_ADDRESS) { const pointerCode = (await rpcCode(header.pointer)).toLowerCase().replace(/^0x/, ""); if (pointerCode.startsWith("00")) { const packed = pointerCode.slice(2); if (packed.length >= 144 && packed.slice(0, 16) === "00a5003000200030") { const comp1 = `0x${packed.slice(16, 80)}` as Hex; const comp2 = `0x${packed.slice(80, 144)}` as Hex; functionScoped = comp1.toLowerCase() === keccak256(addressCompValue(AAVE_V3_BASE.usdc)).toLowerCase() && comp2.toLowerCase() === keccak256(addressCompValue(safeAddress)).toLowerCase(); } } } return { memberAssigned, targetScoped, functionScoped, exact: memberAssigned && targetScoped && functionScoped }; }
export async function readExactRolePermission(modifierAddress: `0x${string}`, safeAddress: `0x${string}`, memberAddress: `0x${string}`): Promise<boolean> { return (await readRolePermissionState(modifierAddress, safeAddress, memberAddress)).exact; }
export async function verifyNegativeRoleProbes(modifierAddress: `0x${string}`, safeAddress: `0x${string}`, memberAddress: `0x${string}`): Promise<boolean> { const roleKey = canonicalRoleKey(); const validWithdrawal = encodeFunctionData({ abi: WITHDRAW_ABI, functionName: "withdraw", args: [AAVE_V3_BASE.usdc, 0n, safeAddress] }); const attacker = "0x0000000000000000000000000000000000000001" as `0x${string}`; const probes = [{ to: AAVE_V3_BASE.pool, value: 1n, data: validWithdrawal, operation: 0 }, { to: AAVE_V3_BASE.pool, value: 0n, data: encodeFunctionData({ abi: WITHDRAW_ABI, functionName: "withdraw", args: [SAFE_ZERO_ADDRESS, 0n, safeAddress] }), operation: 0 }, { to: AAVE_V3_BASE.pool, value: 0n, data: encodeFunctionData({ abi: WITHDRAW_ABI, functionName: "withdraw", args: [AAVE_V3_BASE.usdc, 0n, attacker] }), operation: 0 }, { to: AAVE_V3_BASE.pool, value: 0n, data: "0x12345678" as Hex, operation: 0 }, { to: AAVE_V3_BASE.pool, value: 0n, data: validWithdrawal, operation: 1 }]; for (const call of probes) { try { await rpcCall(modifierAddress, encodeFunctionData({ abi: ROLE_EXEC_ABI, functionName: "execTransactionWithRole", args: [call.to, call.value, call.data, call.operation, roleKey, true] }), memberAddress); return false; } catch { /* expected adversarial rejection */ } } return true; }
